import {
  Airplane,
  AirplaneLanding,
  AirplaneTakeoff,
  Anchor,
  Armchair,
  Backpack,
  Bag,
  BeachBall,
  Bicycle,
  Binoculars,
  Boat,
  Bus,
  CableCar,
  Camera,
  CameraPlus,
  Campfire,
  Car,
  CastleTurret,
  Church,
  Compass,
  CompassRose,
  Confetti,
  Eye,
  Fire,
  Flag,
  Flower,
  ForkKnife,
  Globe,
  House,
  IslandIcon,
  Lighthouse,
  MapPin,
  MapPinArea,
  MapPinLine,
  MapPinPlus,
  MapPinSimple,
  MapTrifold,
  MoonStars,
  Mosque,
  Mountains,
  MusicNotes,
  Park,
  RoadHorizon,
  Sailboat,
  ShoppingBag,
  Signpost,
  Star,
  Storefront,
  Subway,
  Suitcase,
  Sun,
  Synagogue,
  Tag,
  Taxi,
  Tent,
  Ticket,
  Train,
  Tree,
  Umbrella,
  VideoCamera,
  InstagramLogo,
} from "@phosphor-icons/react";

const formatIconLabel = (value) => value.replace(/([a-z])([A-Z])/g, "$1 $2");

const RAW_ICON_OPTIONS = [
  { value: "Airplane", Icon: Airplane },
  { value: "AirplaneTakeoff", Icon: AirplaneTakeoff },
  { value: "AirplaneLanding", Icon: AirplaneLanding },
  { value: "Anchor", Icon: Anchor },
  { value: "Armchair", Icon: Armchair },
  { value: "Backpack", Icon: Backpack },
  { value: "Bag", Icon: Bag },
  { value: "BeachBall", Icon: BeachBall },
  { value: "Bicycle", Icon: Bicycle },
  { value: "Binoculars", Icon: Binoculars },
  { value: "Boat", Icon: Boat },
  { value: "Bus", Icon: Bus },
  { value: "CableCar", Icon: CableCar },
  { value: "Camera", Icon: Camera },
  { value: "CameraPlus", Icon: CameraPlus },
  { value: "Campfire", Icon: Campfire },
  { value: "Car", Icon: Car },
  { value: "CastleTurret", Icon: CastleTurret },
  { value: "Church", Icon: Church },
  { value: "Compass", Icon: Compass },
  { value: "CompassRose", Icon: CompassRose },
  { value: "Confetti", Icon: Confetti },
  { value: "Eye", Icon: Eye },
  { value: "Fire", Icon: Fire },
  { value: "Flag", Icon: Flag },
  { value: "ForkKnife", Icon: ForkKnife },
  { value: "Flower", Icon: Flower },
  { value: "Globe", Icon: Globe },
  { value: "House", Icon: House },
  { value: "Island", Icon: IslandIcon },
  { value: "Lighthouse", Icon: Lighthouse },
  { value: "MapPin", Icon: MapPin },
  { value: "MapPinArea", Icon: MapPinArea },
  { value: "MapPinLine", Icon: MapPinLine },
  { value: "MapPinPlus", Icon: MapPinPlus },
  { value: "MapPinSimple", Icon: MapPinSimple },
  { value: "MapTrifold", Icon: MapTrifold },
  { value: "MoonStars", Icon: MoonStars },
  { value: "Mountains", Icon: Mountains },
  { value: "Mosque", Icon: Mosque },
  { value: "MusicNotes", Icon: MusicNotes },
  { value: "Park", Icon: Park },
  { value: "RoadHorizon", Icon: RoadHorizon },
  { value: "Sailboat", Icon: Sailboat },
  { value: "ShoppingBag", Icon: ShoppingBag },
  { value: "Signpost", Icon: Signpost },
  { value: "Star", Icon: Star },
  { value: "Storefront", Icon: Storefront },
  { value: "Subway", Icon: Subway },
  { value: "Suitcase", Icon: Suitcase },
  { value: "Sun", Icon: Sun },
  { value: "Synagogue", Icon: Synagogue },
  { value: "Tent", Icon: Tent },
  { value: "Ticket", Icon: Ticket },
  { value: "Train", Icon: Train },
  { value: "Tree", Icon: Tree },
  { value: "Umbrella", Icon: Umbrella },
  { value: "VideoCamera", Icon: VideoCamera },
  { value: "Taxi", Icon: Taxi },
  { value: "Tag", Icon: Tag },
  { value: "Instagram", Icon: InstagramLogo },
  { value: "InstagramLogo", Icon: InstagramLogo },
];

export const SIGHT_TAG_ICON_OPTIONS = RAW_ICON_OPTIONS.map((option) => ({
  ...option,
  label: formatIconLabel(option.value),
}));

const ICON_MAP = RAW_ICON_OPTIONS.reduce((acc, option) => {
  acc[option.value] = option.Icon;
  acc[option.value.toLowerCase()] = option.Icon;
  return acc;
}, {});

export const getIconByName = (iconName) => {
  if (!iconName) return null;
  return ICON_MAP[iconName] || ICON_MAP[String(iconName).toLowerCase()] || null;
};
