/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DocsSlugRouteImport } from './routes/docs/$slug'
import { Route as IdeasSlugRouteImport } from './routes/ideas/$slug'
import { Route as PagesIndexRouteImport } from './routes/pages/index'
import { Route as PagesSlugRouteImport } from './routes/pages/$slug'
import { Route as ApiPublicGetPagesRouteImport } from './routes/api/public/get-pages'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsSlugRoute = DocsSlugRouteImport.update({
  id: '/docs/$slug',
  path: '/docs/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const IdeasSlugRoute = IdeasSlugRouteImport.update({
  id: '/ideas/$slug',
  path: '/ideas/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PagesIndexRoute = PagesIndexRouteImport.update({
  id: '/pages/',
  path: '/pages/',
  getParentRoute: () => rootRouteImport,
} as any)
const PagesSlugRoute = PagesSlugRouteImport.update({
  id: '/pages/$slug',
  path: '/pages/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicGetPagesRoute = ApiPublicGetPagesRouteImport.update({
  id: '/api/public/get-pages',
  path: '/api/public/get-pages',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/docs/$slug': typeof DocsSlugRoute
  '/ideas/$slug': typeof IdeasSlugRoute
  '/pages/$slug': typeof PagesSlugRoute
  '/pages/': typeof PagesIndexRoute
  '/api/public/get-pages': typeof ApiPublicGetPagesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/docs/$slug': typeof DocsSlugRoute
  '/ideas/$slug': typeof IdeasSlugRoute
  '/pages/$slug': typeof PagesSlugRoute
  '/pages': typeof PagesIndexRoute
  '/api/public/get-pages': typeof ApiPublicGetPagesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/docs/$slug': typeof DocsSlugRoute
  '/ideas/$slug': typeof IdeasSlugRoute
  '/pages/$slug': typeof PagesSlugRoute
  '/pages/': typeof PagesIndexRoute
  '/api/public/get-pages': typeof ApiPublicGetPagesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/docs/$slug'
    | '/ideas/$slug'
    | '/pages/$slug'
    | '/pages/'
    | '/api/public/get-pages'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/docs/$slug'
    | '/ideas/$slug'
    | '/pages/$slug'
    | '/pages'
    | '/api/public/get-pages'
  id:
    | '__root__'
    | '/'
    | '/docs/$slug'
    | '/ideas/$slug'
    | '/pages/$slug'
    | '/pages/'
    | '/api/public/get-pages'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DocsSlugRoute: typeof DocsSlugRoute
  IdeasSlugRoute: typeof IdeasSlugRoute
  PagesSlugRoute: typeof PagesSlugRoute
  PagesIndexRoute: typeof PagesIndexRoute
  ApiPublicGetPagesRoute: typeof ApiPublicGetPagesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/$slug': {
      id: '/docs/$slug'
      path: '/docs/$slug'
      fullPath: '/docs/$slug'
      preLoaderRoute: typeof DocsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ideas/$slug': {
      id: '/ideas/$slug'
      path: '/ideas/$slug'
      fullPath: '/ideas/$slug'
      preLoaderRoute: typeof IdeasSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pages/': {
      id: '/pages/'
      path: '/pages'
      fullPath: '/pages/'
      preLoaderRoute: typeof PagesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pages/$slug': {
      id: '/pages/$slug'
      path: '/pages/$slug'
      fullPath: '/pages/$slug'
      preLoaderRoute: typeof PagesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/get-pages': {
      id: '/api/public/get-pages'
      path: '/api/public/get-pages'
      fullPath: '/api/public/get-pages'
      preLoaderRoute: typeof ApiPublicGetPagesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DocsSlugRoute: DocsSlugRoute,
  IdeasSlugRoute: IdeasSlugRoute,
  PagesSlugRoute: PagesSlugRoute,
  PagesIndexRoute: PagesIndexRoute,
  ApiPublicGetPagesRoute: ApiPublicGetPagesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
