/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ApiPublicCreateComponentRouteImport } from './routes/api/public/create-component'
import { Route as ApiPublicDeleteComponentRouteImport } from './routes/api/public/delete-component'
import { Route as ApiPublicGetFooterRouteImport } from './routes/api/public/get-footer'
import { Route as ApiPublicGetHeaderRouteImport } from './routes/api/public/get-header'
import { Route as ApiPublicGetPageRouteImport } from './routes/api/public/get-page'
import { Route as ApiPublicGetPagesRouteImport } from './routes/api/public/get-pages'
import { Route as ApiPublicUpdateComponentRouteImport } from './routes/api/public/update-component'
import { Route as ApiPublicUpdateFooterRouteImport } from './routes/api/public/update-footer'
import { Route as ApiPublicUpdateHeaderRouteImport } from './routes/api/public/update-header'

const ApiPublicCreateComponentRoute =
  ApiPublicCreateComponentRouteImport.update({
    id: '/api/public/create-component',
    path: '/api/public/create-component',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicDeleteComponentRoute =
  ApiPublicDeleteComponentRouteImport.update({
    id: '/api/public/delete-component',
    path: '/api/public/delete-component',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicGetFooterRoute = ApiPublicGetFooterRouteImport.update({
  id: '/api/public/get-footer',
  path: '/api/public/get-footer',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicGetHeaderRoute = ApiPublicGetHeaderRouteImport.update({
  id: '/api/public/get-header',
  path: '/api/public/get-header',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicGetPageRoute = ApiPublicGetPageRouteImport.update({
  id: '/api/public/get-page',
  path: '/api/public/get-page',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicGetPagesRoute = ApiPublicGetPagesRouteImport.update({
  id: '/api/public/get-pages',
  path: '/api/public/get-pages',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicUpdateComponentRoute =
  ApiPublicUpdateComponentRouteImport.update({
    id: '/api/public/update-component',
    path: '/api/public/update-component',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicUpdateFooterRoute = ApiPublicUpdateFooterRouteImport.update({
  id: '/api/public/update-footer',
  path: '/api/public/update-footer',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicUpdateHeaderRoute = ApiPublicUpdateHeaderRouteImport.update({
  id: '/api/public/update-header',
  path: '/api/public/update-header',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/api/public/create-component': typeof ApiPublicCreateComponentRoute
  '/api/public/delete-component': typeof ApiPublicDeleteComponentRoute
  '/api/public/get-footer': typeof ApiPublicGetFooterRoute
  '/api/public/get-header': typeof ApiPublicGetHeaderRoute
  '/api/public/get-page': typeof ApiPublicGetPageRoute
  '/api/public/get-pages': typeof ApiPublicGetPagesRoute
  '/api/public/update-component': typeof ApiPublicUpdateComponentRoute
  '/api/public/update-footer': typeof ApiPublicUpdateFooterRoute
  '/api/public/update-header': typeof ApiPublicUpdateHeaderRoute
}
export interface FileRoutesByTo {
  '/api/public/create-component': typeof ApiPublicCreateComponentRoute
  '/api/public/delete-component': typeof ApiPublicDeleteComponentRoute
  '/api/public/get-footer': typeof ApiPublicGetFooterRoute
  '/api/public/get-header': typeof ApiPublicGetHeaderRoute
  '/api/public/get-page': typeof ApiPublicGetPageRoute
  '/api/public/get-pages': typeof ApiPublicGetPagesRoute
  '/api/public/update-component': typeof ApiPublicUpdateComponentRoute
  '/api/public/update-footer': typeof ApiPublicUpdateFooterRoute
  '/api/public/update-header': typeof ApiPublicUpdateHeaderRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/api/public/create-component': typeof ApiPublicCreateComponentRoute
  '/api/public/delete-component': typeof ApiPublicDeleteComponentRoute
  '/api/public/get-footer': typeof ApiPublicGetFooterRoute
  '/api/public/get-header': typeof ApiPublicGetHeaderRoute
  '/api/public/get-page': typeof ApiPublicGetPageRoute
  '/api/public/get-pages': typeof ApiPublicGetPagesRoute
  '/api/public/update-component': typeof ApiPublicUpdateComponentRoute
  '/api/public/update-footer': typeof ApiPublicUpdateFooterRoute
  '/api/public/update-header': typeof ApiPublicUpdateHeaderRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/api/public/create-component'
    | '/api/public/delete-component'
    | '/api/public/get-footer'
    | '/api/public/get-header'
    | '/api/public/get-page'
    | '/api/public/get-pages'
    | '/api/public/update-component'
    | '/api/public/update-footer'
    | '/api/public/update-header'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/api/public/create-component'
    | '/api/public/delete-component'
    | '/api/public/get-footer'
    | '/api/public/get-header'
    | '/api/public/get-page'
    | '/api/public/get-pages'
    | '/api/public/update-component'
    | '/api/public/update-footer'
    | '/api/public/update-header'
  id:
    | '__root__'
    | '/api/public/create-component'
    | '/api/public/delete-component'
    | '/api/public/get-footer'
    | '/api/public/get-header'
    | '/api/public/get-page'
    | '/api/public/get-pages'
    | '/api/public/update-component'
    | '/api/public/update-footer'
    | '/api/public/update-header'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ApiPublicCreateComponentRoute: typeof ApiPublicCreateComponentRoute
  ApiPublicDeleteComponentRoute: typeof ApiPublicDeleteComponentRoute
  ApiPublicGetFooterRoute: typeof ApiPublicGetFooterRoute
  ApiPublicGetHeaderRoute: typeof ApiPublicGetHeaderRoute
  ApiPublicGetPageRoute: typeof ApiPublicGetPageRoute
  ApiPublicGetPagesRoute: typeof ApiPublicGetPagesRoute
  ApiPublicUpdateComponentRoute: typeof ApiPublicUpdateComponentRoute
  ApiPublicUpdateFooterRoute: typeof ApiPublicUpdateFooterRoute
  ApiPublicUpdateHeaderRoute: typeof ApiPublicUpdateHeaderRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/api/public/create-component': {
      id: '/api/public/create-component'
      path: '/api/public/create-component'
      fullPath: '/api/public/create-component'
      preLoaderRoute: typeof ApiPublicCreateComponentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/delete-component': {
      id: '/api/public/delete-component'
      path: '/api/public/delete-component'
      fullPath: '/api/public/delete-component'
      preLoaderRoute: typeof ApiPublicDeleteComponentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/get-footer': {
      id: '/api/public/get-footer'
      path: '/api/public/get-footer'
      fullPath: '/api/public/get-footer'
      preLoaderRoute: typeof ApiPublicGetFooterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/get-header': {
      id: '/api/public/get-header'
      path: '/api/public/get-header'
      fullPath: '/api/public/get-header'
      preLoaderRoute: typeof ApiPublicGetHeaderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/get-page': {
      id: '/api/public/get-page'
      path: '/api/public/get-page'
      fullPath: '/api/public/get-page'
      preLoaderRoute: typeof ApiPublicGetPageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/get-pages': {
      id: '/api/public/get-pages'
      path: '/api/public/get-pages'
      fullPath: '/api/public/get-pages'
      preLoaderRoute: typeof ApiPublicGetPagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/update-component': {
      id: '/api/public/update-component'
      path: '/api/public/update-component'
      fullPath: '/api/public/update-component'
      preLoaderRoute: typeof ApiPublicUpdateComponentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/update-footer': {
      id: '/api/public/update-footer'
      path: '/api/public/update-footer'
      fullPath: '/api/public/update-footer'
      preLoaderRoute: typeof ApiPublicUpdateFooterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/update-header': {
      id: '/api/public/update-header'
      path: '/api/public/update-header'
      fullPath: '/api/public/update-header'
      preLoaderRoute: typeof ApiPublicUpdateHeaderRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  ApiPublicCreateComponentRoute: ApiPublicCreateComponentRoute,
  ApiPublicDeleteComponentRoute: ApiPublicDeleteComponentRoute,
  ApiPublicGetFooterRoute: ApiPublicGetFooterRoute,
  ApiPublicGetHeaderRoute: ApiPublicGetHeaderRoute,
  ApiPublicGetPageRoute: ApiPublicGetPageRoute,
  ApiPublicGetPagesRoute: ApiPublicGetPagesRoute,
  ApiPublicUpdateComponentRoute: ApiPublicUpdateComponentRoute,
  ApiPublicUpdateFooterRoute: ApiPublicUpdateFooterRoute,
  ApiPublicUpdateHeaderRoute: ApiPublicUpdateHeaderRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
